### ISSUE TITLE
Fehler bei Firmware 7.57

### ISSUE THREAD

**Issue by BernhardLinz** [SpookyFM/fritz_route#1]
Mit folgenden Aufruf versuche ich eine Route zu deaktivieren:
`fritz-route --user testuser --password testpassword --url http://192.168.1.198 --network 192.168.128.0 --subnet 255.255.255.0 --gateway 192.168.1.200 --active false`

Erhalte aber die Fehlermeldung:
```
/usr/local/lib/node_modules/fritz-route/node_modules/css-what/lib/commonjs/parse.js:341
                            throw new Error("Pseudo-selector ".concat(name_2, " cannot be quoted"));
                                  ^

Error: Pseudo-selector not cannot be quoted
    at parseSelector (/usr/local/lib/node_modules/fritz-route/node_modules/css-what/lib/commonjs/parse.js:341:35)
    at parse (/usr/local/lib/node_modules/fritz-route/node_modules/css-what/lib/commonjs/parse.js:83:20)
    at Object.select (/usr/local/lib/node_modules/fritz-route/node_modules/cheerio-select/lib/index.js:191:68)
    at LoadedCheerio._findBySelector (/usr/local/lib/node_modules/fritz-route/node_modules/cheerio/dist/commonjs/api/traversing.js:115:30)
    at LoadedCheerio.find (/usr/local/lib/node_modules/fritz-route/node_modules/cheerio/dist/commonjs/api/traversing.js:88:17)
    at QueryRoutes (/usr/local/lib/node_modules/fritz-route/cli.js:178:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/usr/local/lib/node_modules/fritz-route/cli.js:251:23)

Node.js v18.20.4
```

Funktioniert dein Tool noch mit aktuellen FritzBoxen?

**Comment by SpookyFM** [comment]
Hallo,

ich habe leider das Tool selbst nicht mehr in Benutzung und schon lange nicht mehr getestet, ich würde darauf tippen dass sich die Struktur der Web-UI so weit verändert hat dass das Parsen nicht mehr hinhaut. Tut mir leid, aktuell werde ich auch nicht dazu kommen reinzuschauen ob ich einen Fehler sehe.
